### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by baalan92** [CodeDotJS/instavim#6]
While I used -f command, I got the following errors

```
(node:3168) UnhandledPromiseRejectionWarning: HTTPError: Response code 400 (Bad Request)
    at C:\Users\SAKTHYBAALAN\AppData\Roaming\npm\node_modules\instavim\node_modules\got\index.js:129:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:3168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by CodeDotJS** [comment]
Please check [#4](https://github.com/CodeDotJS/instagram-profile-picture/issues/4)
